name: Postgres MCP CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**/README.md'

jobs:
  postgres-mcp-ci:
    runs-on: ubuntu-latest
    container: python:3.12.9-slim-bookworm
    services:
      postgres:
        image: postgresai/extended-postgres
        env:
          POSTGRES_PASSWORD: mysecretpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.x"

      - name: Build
        run: uv sync

      - name: Run Lint
        run: |
          uv run ruff format --check .
          uv run ruff check .

      - name: Run Check
        run: uv run pyright

      - name: Run Tests
        env:
          TEST1_DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/postgres"
        run: uv run pytest -v --log-cli-level=INFO
